### ISSUE TITLE
Working with image watermark in FileModify

### ISSUE THREAD

**Issue by cyclingbatman** [Daniel-KM/FileModify#1]
The text method works in your example but could not get the image watermark to work.

I have used the mogrify command on the terminal and it worked. See below. 

Any ideas on why the convert statement with FileModify and Omeka will not process? 

mogrify -format jpg -matte \
-draw 'gravity south image src-over 0,100 250,250 "/var/www/files/original/watermark.png"' *.jpg

Omeka has encountered an error

Zend_Exception

    Something went wrong with image conversion for file " with the plugin File Modify.

Zend_Exception: Something went wrong with image conversion for file " with the plugin File Modify. in /var/www/plugins/FileModify/FileModifyPlugin.php:283
Stack trace:
#0 /var/www/plugins/FileModify/FileModifyPlugin.php(153): FileModifyPlugin::_convert(Object(File))
#1 /var/www/application/libraries/Omeka/Plugin/Broker.php(157): FileModifyPlugin->hookBeforeSaveFile(Array)
#2 /var/www/application/libraries/Omeka/Record/AbstractRecord.php(298): Omeka_Plugin_Broker->callHook('before_save_fil...', Array)
#3 /var/www/application/libraries/Omeka/Record/AbstractRecord.php(531): Omeka_Record_AbstractRecord->runCallbacks('beforeSave', Array)
#4 /var/www/application/models/Item.php(337): Omeka_Record_AbstractRecord->save()
#5 /var/www/application/models/Item.php(250): Item->saveFiles()
#6 /var/www/application/libraries/Omeka/Record/AbstractRecord.php(277): Item->afterSave(Array)
#7 /var/www/application/libraries/Omeka/Record/AbstractRecord.php(550): Omeka_Record_AbstractRecord->runCallbacks('afterSave', Array)
#8 /var/www/application/libraries/Omeka/Controller/AbstractActionController.php(188): Omeka_Record_AbstractRecord->save(false)
#9 /var/www/application/controllers/ItemsController.php(151): Omeka_Controller_AbstractActionController->addAction()
#10 /var/www/application/libraries/Zend/Controller/Action.php(516): ItemsController->addAction()
#11 /var/www/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
#12 /var/www/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#13 /var/www/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#14 /var/www/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#15 /var/www/application/libraries/Omeka/Application.php(77): Zend_Application->run()
#16 /var/www/admin/index.php(28): Omeka_Application->run()
#17 {main}

**Comment by Daniel-KM** [comment]
Hi,
Sorry, I forgot your message.
The plugin is designed for `convert`. Else you can modify directly the file `libraries/FileModify/Preprocess.php`.

**Comment by cyclingbatman** [comment]
I was trying to use the two examples provided in docs. I could only get the
text one working.

I will look into using the preprocess method.

Thank you.

**Comment by cyclingbatman** [comment]
As of now we have used your plugin with great success. Thank you for providing this feature. 

We have been looking at Omeka S version to use on new sites. This watermark feature is something we would still like to continue to use but see it is not available as a module in Omeka S. I just wanted to let you know so if in the future you might think of adding to new version you would have some users that would use it.

**Comment by cyclingbatman** [comment]
Would anyone have any idea if this could be updated by others or is copyrighted? Is it possible to pay to update this by the owner?
